# Created with YamlCreate.ps1 v2.2.1 $debug=NVS1.CRLF.5-1-19041-1682.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Apache.Ignite
PackageVersion: 3.0.0
MinimumOSVersion: 10.0.0.0
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://dlcdn.apache.org/ignite/3.0.0/ignite3-db-3.0.0.msi
  InstallerSha256: 13AEFA9714F821784107A5BA68F3A11BC89E105827CA505E0AA3B047E60DF90E
  ProductCode: '{EA0F7BB4-0F6D-48CA-BEAD-333929D583CB}'
ManifestType: installer
ManifestVersion: 1.2.0
