# Created with YamlCreate.ps1 v2.2.1 $debug=NVS1.CRLF.5-1-19041-1682.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Apache.Ignite
PackageVersion: 3.0.0
PackageLocale: en-US
Publisher: The Apache Software Foundation
PublisherUrl: https://apache.org/
# PublisherSupportUrl:
PrivacyUrl: https://www.apache.org/foundation/policies/privacy.html
# Author:
PackageName: Apache Ignite
PackageUrl: https://ignite.apache.org/
License: Apache License 2.0
LicenseUrl: https://www.apache.org/licenses/LICENSE-2.0
Copyright: © 2015 - 2022 The Apache Software Foundation.
# CopyrightUrl:
ShortDescription: Distributed Database For High-Performance Applications With In-Memory Speed
# Description:
Moniker: ignite
# Tags:
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.2.0
